on:
  push:
    branches:
      - master

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install npm dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        run: npm install

      - name: Setup .env
        run: cp .env.example .env

      - uses: cschleiden/replace-tokens@v1
        with:
          files: '.env'
        env:
          TESTS_NOTION_EMAIL: ${{ secrets.TESTS_NOTION_EMAIL }}
          TESTS_NOTION_PASS: ${{ secrets.TESTS_NOTION_PASS }}

      - name: Test Code
        uses: mujo-code/puppeteer-headful@18.9.0
        env:
          CI: 'true'
        with:
          args: npm test
